---
- name: 创建 Xray 工作目录
  file:
    path: "{{ xray_project_dir }}"
    state: directory
    owner: "{{ xray_owner }}"
    group: "{{ xray_group }}"
    mode: '0755'

- name: 下发 Xray 配置文件 (config.json)
  template:
    src: config.json.j2
    dest: "{{ xray_project_dir }}/config.json"
    owner: "{{ xray_owner }}"
    group: "{{ xray_group }}"
    mode: '0644'
  notify: Restart Xray
  no_log: true

- name: 下发 Xray Docker Compose 文件
  template:
    src: docker-compose.yml.j2
    dest: "{{ xray_project_dir }}/docker-compose.yml"
    owner: "{{ xray_owner }}"
    group: "{{ xray_group }}"
    mode: '0644'
  notify: Restart Xray

- name: 启动 Xray 容器
  community.docker.docker_compose_v2:
    project_src: "{{ xray_project_dir }}"
    state: present
  when: xray_manage_runtime | bool
