---
private_state_dir: "{{ playbook_dir }}/.local.example"

system_timezone: Etc/UTC

base_domain: example.com
backup_keep_local: 7
backup_keep_remote: 14

deploy_node_xray_under_caddy: vps-a.example.com
deploy_node_logto: vps-b.example.com
deploy_node_logto_gateway: vps-a.example.com
deploy_node_sftpgo: vps-a.example.com
deploy_node_sftpgo_gateway: vps-a.example.com
zammad_enabled: true
deploy_node_zammad: vps-b.example.com
deploy_node_postgres: vps-b.example.com
deploy_node_mailcow: vps-b.example.com
