---
proxy_control_plane_node_sync_enabled: false
proxy_control_plane_api_url: http://127.0.0.1:9710""
proxy_control_plane_admin_email: ""
proxy_control_plane_admin_password: ""
proxy_control_plane_access_token: ""
proxy_control_plane_validate_certs: true
proxy_control_plane_request_timeout: 20
proxy_control_plane_default_region: ""
proxy_control_plane_xray_under_caddy_public_port: 443
proxy_control_plane_xray_under_caddy_transport: ws
proxy_control_plane_xray_under_caddy_security: tls
proxy_control_plane_xray_under_caddy_path: /v2ray
proxy_control_plane_xray_public_port: 443
proxy_control_plane_xray_transport: tcp
proxy_control_plane_xray_security: reality
proxy_control_plane_xray_fingerprint: chrome
proxy_control_plane_runtime_api_enabled: false
proxy_control_plane_runtime_api_host: ""
proxy_control_plane_runtime_api_tag: proxy-control-plane-api
proxy_control_plane_runtime_inbound_tag: proxy-control-plane-vless-in
proxy_control_plane_xray_runtime_api_port: 10085
proxy_control_plane_xray_under_caddy_runtime_api_port: 10086
