---
- name: Restart Proxy Control Plane
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_control_plane_project_dir }}"
    state: restarted
  when: proxy_control_plane_manage_runtime | bool
