---
xray_image: "ghcr.io/xtls/xray-core:25.8.3"
xray_project_dir: /opt/xray
xray_owner: root
xray_group: root
xray_manage_runtime: true
proxy_control_plane_runtime_api_enabled: false
proxy_control_plane_runtime_api_host: ""
proxy_control_plane_runtime_api_tag: proxy-control-plane-api
proxy_control_plane_runtime_inbound_tag: proxy-control-plane-vless-in
proxy_control_plane_xray_runtime_api_port: 10085
