---
caddy_image: "caddy:2.11.2"
proxy_control_plane_subscription_proxy_enabled: false
proxy_control_plane_subscription_proxy_upstream: "http://127.0.0.1:9710"
proxy_control_plane_subscription_public_path: /xray/sub
