---
ansible:
  env:
    ANSIBLE_FORCE_COLOR: "1"
  playbooks:
    converge: converge.yml
    verify: verify.yml

dependency:
  name: galaxy
  enabled: false

prerun: false

scenario:
  name: default
  test_sequence:
    - syntax
    - converge
    - idempotence
    - verify
