---
zammad_env_template_src: "{{ private_state_dir | default(playbook_dir ~ '/.local') }}/role_vars/zammad/zammad.env.j2"
zammad_sync_script_path: /opt/zammad/zammad_sync.sh
zammad_backup_local_log_file: /var/log/zammad_backup_local.log
zammad_backup_cloud_log_file: /var/log/zammad_backup_cloud.log
zammad_backup_cron_file: zammad_sync
zammad_backup_cron_minute: "0"
zammad_backup_local_cron_hour: "6"
zammad_backup_cloud_cron_hour: "18"
